import './globals.css';

import type { Metadata } from 'next';
import { Suspense } from 'react';
import Providers from '@/components/Providers';
import { pretendard } from '@/theme/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={pretendard.className}>
        <Suspense>
          <Providers>{children}</Providers>
        </Suspense>
      </body>
    </html>
  );
}

// /**
//  * 정적 메타데이터를 설정할 경우
//  * @docs https://nextjs.org/docs/app/building-your-application/optimizing/metadata#static-metadata
//  */
// export const metadata: Metadata = {
//   metadataBase: new URL('https://example.com'), // prefix url => 아래의 속성들에서 경로들을 상대경로로 작성할 수 있음
//   title: '웹사이트 제목을 입력해주세요.',
//   description: '웹사이트 설명을 입력해주세요.',
//   openGraph: {
//     locale: 'ko_KR',
//     type: 'website',
//     siteName: '웹사이트 이름을 입력해주세요.',
//     url: `/`,
//     images: [`/assets/images/opengraph-image.png`],
//     icons,
//     manifest: '/favicons/manifest.json',
//   },
// };

// /**
//  * @docs https://nextjs.org/docs/app/api-reference/functions/generate-metadata
//  */
// export async function generateMetadata(_: unknown, state: ResolvingMetadata): Promise<Metadata> {
//   const pathname = getPathnameFromMetadataState(state) ?? '';

//   try {
//     // 공통 SEO 조회
//     const commonSeo = await getCommonSeoApi();
//     // 페이지 SEO 조회
//     let pageSeo: GetPageSeoResponseDto;
//     try {
//       pageSeo = await getPageSeoApi({ pageUrl: pathname });
//     } catch (_err) {
//       /**
//        * 관리자 페이지에서 등록하지 않은 페이지는 백엔드에서 4XX으로 응답이 넘어오므로 빈 객체로 처리
//        * statusCode:400
//        * errorMessage: "해당 페이지 URL은 존재하지 않습니다."
//        */
//       pageSeo = {} as GetPageSeoResponseDto;
//     }

//     return {
//       title: pageSeo?.metaTitle || commonSeo.metaTitle,
//       description: pageSeo?.metaDescription || commonSeo.metaDescription,
//       openGraph: {
//         locale: 'ko_KR',
//         type: 'website',
//         url: pageSeo?.ogUrl || commonSeo.ogUrl,
//         title: pageSeo?.ogTitle || commonSeo.ogTitle,
//         description: pageSeo?.ogDescription || commonSeo.ogDescription,
//         images: [pageSeo?.ogImageUrl || commonSeo.ogImageUrl],
//       },
//       icons,
//       manifest: '/favicons/manifest.json',
//     };
//   } catch (_err) {
//     console.log(_err);
//     return {};
//   }
// }

/**
 * @docs https://nextjs.org/docs/app/building-your-application/optimizing/metadata#json-ld
 */
// export const jsonLd: WithContext<Organization> = {
//   '@context': 'https://schema.org',
//   '@type': 'Organization',
//   url: FRONT_URL,
//   name: '웹사이트 이름을 입력해주세요.',
//   description: '웹사이트 설명을 입력해주세요.',
//   sameAs: [
//     // ' https://www.youtube.com/유튜브_주소',
//     // 'https://blog.naver.com/네이버 블로그_주소',
//     // 'https://www.instagram.com/인스타그램_주소/',
//   ],
// };
